spark.jars.packages                                   org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.3
spark.sql.extensions                                org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.local                             org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type                        hadoop
spark.sql.catalog.local.warehouse                   /opt/bitnami/spark/data/iceberg
